/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Welcomeentity model module.
 * @module model/Welcomeentity
 * @version 1.0.0
 */
class Welcomeentity {
    /**
     * Constructs a new <code>Welcomeentity</code>.
     * @alias module:model/Welcomeentity
     * @param title {String} 
     */
    constructor(title) { 
        
        Welcomeentity.initialize(this, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title) { 
        obj['title'] = title;
    }

    /**
     * Constructs a <code>Welcomeentity</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Welcomeentity} obj Optional instance to populate.
     * @return {module:model/Welcomeentity} The populated <code>Welcomeentity</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Welcomeentity();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Welcomeentity.prototype['_id'] = undefined;

/**
 * @member {String} title
 */
Welcomeentity.prototype['title'] = undefined;






export default Welcomeentity;

